//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaTruc
    {
        public int MaCT { get; set; }
        public System.DateTime NgayTruc { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBD { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKT { get; set; }
    
        public virtual DoanhThu DoanhThu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
