//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoanhThu()
        {
            this.CaTrucs = new HashSet<CaTruc>();
        }
    
        public int MaCT { get; set; }
        public System.DateTime NgayTruc { get; set; }
        public Nullable<long> DoanhThuCT { get; set; }
        public Nullable<long> DoanhThuNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaTruc> CaTrucs { get; set; }
    }
}
